name: Babashka
on: [push, pull_request]
jobs:
  clojure:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.727

      - name: Install bb (dev)
        run: |
          bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --version 1.0.168-SNAPSHOT

      - name: Run tests
        run: bb test:bb

